spring:
  datasource:
    password: pwdpwdpwd
    url: jdbc:mysql://192.168.22.61:3306/lojalivros
    username: lojalivros
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        
    show-sql: true
